### ISSUE TITLE
能否出个把本地已有的英文tag替换成中文tag的功能

### ISSUE THREAD

**Issue by Kelcoin** [zhy201810576/ETagCN#1]
RT，重新刮削需要好几天的时间
希望能出个直接替换本地Tag的功能，这样可以很方便从原版插件替换成这个插件

**Comment by zhy201810576** [comment]
你好，你的需求我已收到，由于我不擅长Perl语言，所以我不敢保证一定能开发你提出的功能，但我会尽力尝试，希望你能理解☺

**Comment by Kelcoin** [comment]
理解理解
我不会编程，只能提个issue，大佬尽力而为

**Comment by zhy201810576** [comment]
你好，你需求的功能我已开发完成，详情请访问[ETagConverter - LANraragi 英文标签批量翻译脚本](https://github.com/zhy201810576/ETagConverter)。
**特别注意：为了你的数据安全，在使用上述脚本前请务必做好数据备份**

**Comment by Kelcoin** [comment]
> 

<img width="428" alt="image" src="https://user-images.githubusercontent.com/10922375/227592310-1f324b8d-9983-4d67-a9f9-ac4b1377bcb3.png">
非常感谢，测试了一下效果非常好，五万多本替换只用了一分多钟
搜索在重建索引后也正常使用
如有问题我再行汇报
