### ISSUE TITLE
运行插件提示连接超时，请问这是啥情况呀？

### ISSUE THREAD

**Issue by p199654** [zhy201810576/ETagCN#2]
处理 ID d37126d0019cca3b510df6500af0d76dc33ab81e (Connect timeout at /root/lanraragi/script/../lib/LANraragi/Plugin/Metadata/ETagCN.pm line 242.
)时发生插件错误

**Comment by zhy201810576** [comment]
你好，可能由以下几种原因导致：
1. 没有配置前置登录插件`E-Hentai`的相关cookie
2. 需要科学上网，P.S. 获取`Ex-Hentai`的元数据需要美国IP
3. 获取元数据过于频繁，可尝试多获取几次或等待一会儿，也可以切换IP地址

**Comment by p199654** [comment]
![20230425095059](https://user-images.githubusercontent.com/17405323/234154872-1c1597ca-be04-4401-960e-7be2bf21aca9.png)
我手动获取又是正常的，梯子挂了。
star cookie这个需要填写么？
登录插件版本：E-Hentai v.2.2 by Difegue

**Comment by p199654** [comment]
哦，我大致知道了，可能梯子IP不是美国的，获取的tag不是里站的，我在试试。

**Comment by zhy201810576** [comment]
那可能是获取元数据过于频繁，如果一次性添加太多内容就会出现这种情况。
插件有一项设置可以强制走里站获取元数据：
![debug-01](https://raw.githubusercontent.com/zhy201810576/ETagCN/master/img/7e7086250844563742a14b6a1159896a.png)

**Comment by zhy201810576** [comment]
`star cookie`是捐赠用户特权，拥有在表站访问里站内容的权限。

- 如果你的账号拥有访问里站的权限，且梯子IP地址是欧美地区IP，就不用考虑这个了。
- 你的账号拥有访问里站的权限，但是梯子IP地址是非欧美地区IP，就需要添加`igneous cookie`，这个选项在登录插件v2.3已修复。

**Comment by p199654** [comment]
汉化版LANraragi只有2.2版本，2.3插件能单独更新么？还是只能升级最新的原版？

**Comment by zhy201810576** [comment]
应该可以单独更新
