### ISSUE TITLE
使用标题搜索时搜不到画廊的bug

### ISSUE THREAD

**Issue by satanikia1300** [zhy201810576/ETagCN#6]
最近一直没法自动匹配到画廊，发现插件搜索的时候会在标题左右加上引号，去掉引号就能正常搜索了。。。

https://github.com/zhy201810576/ETagCN/blob/64f05eab28aec7561df46872c5cbc727bc286432/ETagCN.pm#L162

**Comment by zhy201810576** [comment]
感谢指正😊
